/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import accesOracle.DaoAdherent;
import accesOracle.DaoEmploye;
import controlleur.ModeleTableEmploye;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author LeHoangDinh
 */
public class FenetreManager extends javax.swing.JFrame {

    /**
     * Creates new form FenetreManager
     */
         private DaoEmploye leDaoEmp;
    private DaoAdherent leDaoAdh;
    private ModeleTableEmploye leModele;
    
    public FenetreManager(ModeleTableEmploye leModele, DaoAdherent leDaoA, DaoEmploye leDaoE) throws SQLException {
         this.leDaoEmp = leDaoE;
        this.leDaoAdh = leDaoA;
        this.leModele = leModele; 
        initComponents();
        
                try {
            leModele.charger();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Chargement impossible", "alerte", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manager");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(188, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel1)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
