/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import controlleur.ModeleTable;
import javax.swing.JOptionPane;
import metier.Adherent;
import metier.Employe;

/**
 *
 * @author P1313115
 */
public class FenetreAffichage extends javax.swing.JFrame {

    private ModeleTable leModele;

    /**
     * Creates new form FenetreAffichage
     */
    public FenetreAffichage(ModeleTable leModele) {
        this.leModele = leModele;

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        laTable = new javax.swing.JTable();
        btSuppression = new javax.swing.JButton();
        btInsertion = new javax.swing.JButton();
        btConnexion = new javax.swing.JButton();
        txId = new javax.swing.JTextField();
        txMdp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jltest = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Affichage des étudiants du département Info");

        laTable.setModel(leModele);
        laTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(laTable);

        btSuppression.setText("Supprimer");
        btSuppression.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSuppressionActionPerformed(evt);
            }
        });

        btInsertion.setText("Insérer");
        btInsertion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertionActionPerformed(evt);
            }
        });

        btConnexion.setText("Connexion");
        btConnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConnexionActionPerformed(evt);
            }
        });

        jLabel1.setText("Identifiant");

        jLabel2.setText("MDP");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txMdp, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btConnexion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jltest, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btInsertion)
                    .addComponent(btSuppression))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btInsertion)
                        .addComponent(jLabel1))
                    .addComponent(txId, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jltest, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSuppression)
                            .addComponent(btConnexion)
                            .addComponent(jLabel2))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSuppressionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSuppressionActionPerformed
        int numeroLigne = laTable.getSelectedRow();
        if (numeroLigne != -1) {
            leModele.supprimer(numeroLigne);
        }


    }//GEN-LAST:event_btSuppressionActionPerformed

    private void btInsertionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertionActionPerformed
        String str = "toto";
        String tx = txId.getText().toString();
        if (str.equalsIgnoreCase(tx)) {
            JOptionPane.showMessageDialog(null, "connecté", "alert", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, " pas connecté", "alert", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btInsertionActionPerformed

    private void btConnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConnexionActionPerformed

        try {
            String MonId = "";
            String MonMot = "";
            boolean ok = false;

            for (int i = 0; i < laTable.getRowCount(); i++) {
                MonId = laTable.getValueAt(i, 0).toString();
                MonMot = laTable.getValueAt(i, 5).toString();
                if (txId.getText().equalsIgnoreCase(MonId)
                        && txMdp.getText().equalsIgnoreCase(MonMot)) {
                    ok = true;
                    JOptionPane.showMessageDialog(null, "connecté", "alert", JOptionPane.ERROR_MESSAGE);
                    Employe emp = new Employe();
                    // FenetreCoach laFenetre = new FenetreCoach(this,emp);
                }
                i++;
            }
            if (ok == false) {
                JOptionPane.showMessageDialog(null, "pas connecté", "alert", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "erreur" + ex, "alert", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btConnexionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConnexion;
    private javax.swing.JButton btInsertion;
    private javax.swing.JButton btSuppression;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jltest;
    private javax.swing.JTable laTable;
    private javax.swing.JTextField txId;
    private javax.swing.JTextField txMdp;
    // End of variables declaration//GEN-END:variables

}
